import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import Head from './components/Head';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Head />
      {children}
      </body>
    </html>
  );
}
//<Head />
